services:
  - type: web
    name: spotify-sorter
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SPOTIPY_CLIENT_ID
        sync: false
      - key: SPOTIPY_CLIENT_SECRET
        sync: false
      - key: SPOTIPY_REDIRECT_URI
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 300"
